name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.3.0
  web_socket_channel: ^2.4.0
  http: ^1.2.2
  provider: ^6.0.5

  cupertino_icons: ^1.0.8
  image_picker: ^0.8.6
   
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
assets:
    - src/artifacts/HealthcareRecord.json
    - assets/images/default_image.png
